deploy:
  needs: push-image
  runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        host_key_check: false
        script_stop: false
        timeout: 60s
        command_timeout: 60s
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/simple-api:latest
          docker stop simple-api || true
          docker rm simple-api || true
          docker run -d --name simple-api \
            -p 80:3000 \
            --restart=always \
            ${{ secrets.DOCKERHUB_USERNAME }}/simple-api:latest
